### ISSUE TITLE
Use C++

### ISSUE THREAD

**Issue by joaomello** [leicht/TuxPLC#10]
Hi all!
Is bad idea pass to C++ with unit tests and good wiki about the protocol? I would like to help. Just an idead.

**Comment by influenza** [comment]
Let's keep the project in C. I am interested in converting or removing the Java files as well. Plain C, on a modern compiler, has excellent portability and can accomplish anything this project is after.

Unit tests are a great idea. I have used [greatest](https://github.com/silentbicycle/greatest) on other C projects and found it to be lightweight and easy to use. I will notify you when I get some sample test cases in place.

Closing.
