### ISSUE TITLE
Recive messages from PLC

### ISSUE THREAD

**Issue by joaomello** [leicht/TuxPLC#4]
Hi, there is a way to receive messages from PLC? Like, not read in intervals but receive a "callback" from PLC.

**Comment by thatcadguy** [comment]
I believe the communication is always a "pull" style, never "push".

**Comment by evaldes2015** [comment]
The Ethernet/IP protocol supports this but tuxeip does not.

**Comment by influenza** [comment]
Closing this issue. Please add further discussion to the enhancement issue, #13
