### ISSUE TITLE
Visual Studio solution

### ISSUE THREAD

**Issue by mesta1** [leicht/TuxPLC#7]
In the old repository (http://code.google.com/p/tuxeip/) there was a folder "windows" that contained the Visual Studio solution files.
Can you add it back please ?

**Comment by joaomello** [comment]
HI, you can execute CMake, it will generate an Visual Studio solution.

**Comment by joaomello** [comment]
Hi @mesta1 works? (:

**Comment by mesta1** [comment]
I still have to test it. By the way is it possible to change the license of this project in something less restrictive ? Maybe a LGPL, BSD, MIT etc...
GPL was good time ago, but now it's too restrictive.

**Comment by joaomello** [comment]
@leicht

**Comment by influenza** [comment]
Closing as off topic
