### ISSUE TITLE
RegisterSession is not woking on windows

### ISSUE THREAD

**Issue by joaomello** [leicht/TuxPLC#9]
I always recive an erro on RegisterSession fallowing test2.c, this is my log error:

Starting, Pid = 416
entering OpenSession
OpenSession Ok
entering RegisterSession
.CipSendData : 4
008EF8EC (0000) :       65 00 04 00 00 00 00 00 00 00
008EF8F6 (0010) :       00 00 00 00 00 00 00 00 00 00
008EF900 (0020) :       00 00 00 00 01 00 00 00
.CipRecvData : -2

Error : RegisterSession Unsolicited Message (-7:0)
entering CloseSession

What can I doing wrong?

**Comment by joaomello** [comment]
On windows MSG_WAITALL at https://github.com/leicht/TuxPLC/blob/master/tuxeip/src/SendData.c#L199 must be 0.

**Comment by KutapiAise** [comment]
can you provide me with  a link to windows solution for TUXPLC. I seem to have the same problem with the RegisterSession!!
